### ISSUE TITLE
CLI

### ISSUE THREAD

**Issue by chocol4te** [srijs/rust-crc32fast#10]
Hey, I'd like to work on a CLI for this library, I'm tired of using `cksum` and other CRC tools at pretty slow speeds when I know my machine can go a lot faster with this library.

If I worked on it, is it the sort of thing you'd like to see merged?

**Comment by srijs** [comment]
Did you end up building the tool?

Generally speaking, my goal for this repo is fairly focussed on providing a library for CRC32. I think a tool like that could be useful, but I don't see why it would need to live inside this repository.

**Comment by chocol4te** [comment]
I did, I lost the work but it was only ~10 lines I could easily write again. If it lived inside this repo, it would mean someone could both add `crc32fast` to their Cargo.toml as a library, or use `cargo install crc32fast` to get the CLI. Keeping both inside the same repo would be convenient for releases as once written I don't see any need to modify the CLI, but if you'd rather not I'm cool with that too :)

**Comment by srijs** [comment]
Closing this as won't-fix.
