### ISSUE TITLE
Erroneous dependency specification in some unyanked versions

### ISSUE THREAD

**Issue by Tamschi** [srijs/rust-crc32fast#18]
Some version of this crate depend on `rustc_version` with too low a minimum version.

You can test this by checking out the affected version (or making a project that depends on each version) and running

```cmd
cargo +nightly update -Z minimal-versions && cargo +nightly check
```

Affected versions (possibly incomplete, my build already does not resolve earlier):
- 1.0.1
- 1.0.2
- 1.0.3
- 1.0.4
- 1.1.0

Fixed in:
- 1.1.1

This [breaks my CI](https://github.com/Tamschi/adb-dump/runs/1783123140?check_suite_focus=true#step:6:43) as follows:

<details><summary>Build Log</summary>

```sh
> cargo +nightly update -Z minimal-versions && cargo +nightly check --jobs 1
    Updating crates.io index
   Compiling crc32fast v1.0.1
error[E0277]: the trait bound `Version: From<({integer}, {integer}, {integer})>` is not satisfied
 --> […]\.cargo\registry\src\github.com-1ecc6299db9ec823\crc32fast-1.0.1\build.rs:8:30
  |
8 |     if version >= (1, 27, 0).into() {
  |                              ^^^^ the trait `From<({integer}, {integer}, {integer})>` is not implemented for `Version`
  |
  = help: the following implementations were found:
            <Version as From<semver_parser::version::Version>>
  = note: required because of the requirements on the impl of `Into<Version>` for `({integer}, {integer}, {integer})`

error: aborting due to previous error

For more information about this error, try `rustc --explain E0277`.
error: could not compile `crc32fast`

To learn more, run the command again with --verbose.
```

</details>

- - -

Since this is already fixed in newer versions that are semver-compatible, it would be enough to yank all of the affected versions to stop `cargo +nightly update -Z minimal-versions` from resolving to them.

Doing so fixes the issue transitively for any projects that depend on this one, so maintainers there would not have to do anything.

**Comment by srijs** [comment]
Closing because we've since removed this dependency, and the `minimal-versions` is green now!
