### ISSUE TITLE
Fails to build on the latest nightly for AArch64 when using the `nightly` feature

### ISSUE THREAD

**Issue by AlexTMjugador** [srijs/rust-crc32fast#33]
Hi, thanks for your work on this useful library! 😄

As stated in the issue title, `crc32fast` fails to build on the latest nightly (`rustc 1.78.0-nightly (d44e3b95c 2024-02-09)`) for AArch64 targets due to an unstable feature that was removed:

![Build error](https://github.com/srijs/rust-crc32fast/assets/7822554/2ebe04ee-972e-4e49-9539-823d8cab2719)

This is a fairly recent regression: nightlies older than a week or so are unaffected.

The Rust tracking issue for the removed `stdsimd` feature has already been referenced by other affected projects: https://github.com/rust-lang/rust/issues/48556

**Comment by srijs** [comment]
Thanks, fixed in 3580338b07a098b20288645e1c6126cf5f187f75 and released in v1.4.0. Please let me know if you encounter any other issues!

**Comment by AlexTMjugador** [comment]
Now it builds fine again, thanks for the quick fix! :+1:
