### ISSUE TITLE
"the paper"

### ISSUE THREAD

**Issue by lolbinarycat** [srijs/rust-crc32fast#34]
`src/specialized/pclmulqdq.rs` references "the paper" several times, and as far as i can tell, none of the files in this repo mentions any paper whatsoever.

**Comment by AlexTMjugador** [comment]
Based on the source code comments about the algorithm's implementation on Linux, the listed steps, and the values of the `Kx` constants, it seems very likely that "the paper" refers to ["Fast CRC Computation for Generic Polynomials Using PCLMULQDQ Instruction"](https://fossies.org/linux/zlib-ng/doc/crc-pclmulqdq.pdf), an influential 2009 whitepaper by V Gopal, E Ozturk, J Guilford, G Wolrich, W Feghali, et al., most of which were Intel engineers at the time.

**Comment by srijs** [comment]
Yep, that's correct @AlexTMjugador! If you want to send a PR to adjust the docs, would be happy to merge it!

**Comment by srijs** [comment]
Fixed via #40.
