### ISSUE TITLE
Consider adding support for other CRC polynomials

### ISSUE THREAD

**Issue by NeoLegends** [srijs/rust-crc32fast#7]
I think https://github.com/BurntSushi/rust-snappy could really profit from using this crate (because they currently hand-roll their CRC implementation), but it requires the Castagnoli polynomial, so it cannot use this crate.

Do you think it would be feasible to implement support for different polynomials for crc32fast?

**Comment by srijs** [comment]
It looks like there is an open PR to add a dependency on `crc32c` (https://github.com/BurntSushi/rust-snappy/pull/20), which has hardware support on x86_64.

What benefits do you see in this crate supporting additional polynomials, if there are already crates out there that specifically target the Castagnoli polynomial, including hardware support?

**Comment by NeoLegends** [comment]
> Out of curiosity, what benefits do you see in this crate supporting additional polynomials, if there are already crates out there that specifically target the Castagnoli polynomial, including hardware support?

Ah, I didn't actually know the others had hardware support as well. My reasoning was that it would be beneficial to have a one-stop-shop solution with hardware support for all / most CRC polynomials.
